# Generated by Django 4.2 on 2023-04-17 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data_adicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data_adicao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
