from distutils.core import setup
from Cython.Build import cythonize

# setup(name='cython_example.pyx') # cython_example.pyx is the name of the file that will be generated by cython, accept list of files
setup(
    ext_modules=cythonize(["cumprimenta.pyx", "computa.pyx"])
)
